import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Fingerprint, Globe2, Layers, LockKeyhole, ShieldCheck, Sparkles, CircleDollarSign, KeyRound } from "lucide-react";
import { QuickGenerator } from "@/components/ssl/quick-generator";
import { GlassButton } from "@/components/ui/glass-button";
import { site, pageMetadata } from "@/config/site";

export const metadata = pageMetadata("Free SSL Certificate Generator - Let's Encrypt", site.description, "/");

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-inner"><div className="eyebrow"><span className="status-dot" /> A more secure web starts here</div><h1>Free SSL certificates.<br /><span>Zero unnecessary steps.</span></h1><p className="hero-description">Secure your domain with Let&apos;s Encrypt.<br className="desktop-break" /> No account, no payment, just a safer connection.</p><div className="hero-tool"><QuickGenerator /></div><div className="trust-row">{["Powered by Let's Encrypt", "No account required", "Wildcard support"].map((text) => <span key={text}><Check size={15} />{text}</span>)}</div></div></section>
    <section className="platform-strip"><div className="container"><p>YOUR DOMAIN. YOUR SERVER. YOUR CERTIFICATE.</p><div>{["Nginx", "Apache", "cPanel", "HestiaCP", "CloudPanel", "Node.js", "Docker"].map((platform) => <span key={platform}>{platform}</span>)}</div></div></section>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">Less friction. More protection.</span><h2>Everything you need.<br />Nothing you don&apos;t.</h2></div><p>Trusted certificates without the account setup.<br />Built for the people building the web.</p></div><div className="benefit-grid">{([
      [CircleDollarSign, "Free, from start to finish", "No plans to compare or payment details to enter. Certificates are issued free of charge."],
      [ShieldCheck, "Trust that travels", "Let's Encrypt certificates are trusted by modern browsers and operating systems."],
      [Fingerprint, "No account required", "Get straight to your certificate. No signup forms, passwords, or login wall."],
      [Sparkles, "One wildcard. More coverage.", "Secure subdomains with a wildcard certificate using DNS ownership validation."],
      [Layers, "Multiple domains, one certificate", "Include your root domain, www, and other hostnames in a single SAN certificate."],
      [KeyRound, "Your key stays with you", "Certificate keys are created in your browser. Only the signed CSR reaches our server."],
    ] as const).map(([Icon, title, text], index) => <article className="benefit" key={title}><div className={`benefit-icon accent-${index % 3}`}><Icon size={23} /></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="how-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">From domain to download</span><h2>Three steps to a safer site.</h2></div><Link href="/guides" className="text-link">Explore installation guides <ArrowUpRight size={17} /></Link></div><div className="how-grid">{[["01", "Enter your domain", "Add the hostnames you want to secure. Choose DNS or HTTP verification."], ["02", "Prove it's yours", "Add a DNS record or upload a challenge file. Let's Encrypt checks ownership."], ["03", "Make it official", "Download your certificate and private key, then install them on your server."]].map(([number, title, text]) => <article key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section container supported-section"><div><span className="eyebrow">Small site. Big project. Same protection.</span><h2>A certificate for<br />every kind of domain.</h2><p>Standard, subdomain, wildcard, and multi-domain certificates, all through the same straightforward flow.</p><Link href="/generate" className="text-link">Find your certificate <ArrowRight size={17} /></Link></div><div className="domain-examples">{[["example.com", "Standard domain"], ["app.example.com", "Subdomain"], ["*.example.com", "Wildcard"], ["example.com + www.example.com", "Multi-domain / SAN"]].map(([domain, type]) => <div key={domain}><Globe2 size={19} /><code>{domain}</code><span>{type}</span></div>)}</div></section>
    <section className="ca-section"><div className="container ca-inner"><div className="ca-symbol"><LockKeyhole size={36} /></div><div><span className="eyebrow">A public good, built on open standards</span><h2>Powered by Let&apos;s Encrypt.</h2><p>Let&apos;s Encrypt is a nonprofit certificate authority helping make HTTPS the default. {site.name} connects you to its ACME service, with a simple way to prove domain ownership and download your files.</p><a className="text-link" href="https://letsencrypt.org/about/" target="_blank" rel="noreferrer">About Let&apos;s Encrypt <ArrowUpRight size={17} /></a></div></div></section>
    <section className="section container home-faq"><div><span className="eyebrow">Good questions. Clear answers.</span><h2>A little clarity<br />before you start.</h2><Link href="/faq" className="text-link">All frequently asked questions <ArrowRight size={17} /></Link></div><div>{[["Is it really free?", "Yes. Let's Encrypt issues certificates at no charge. You don't need an account or payment details to use this service."], ["Can I generate a wildcard certificate?", "Yes. Enter *.example.com and use DNS validation. Add example.com separately if you also need to cover the root domain."], ["Do you store my private key?", "No. Your certificate key is generated in browser memory and is not sent to the server. Download it before leaving or refreshing the page."], ["Will my certificate renew automatically?", "No. This is a manual issuance tool. Renew before your certificate's actual expiry date, or use an automated ACME client on your server."]].map(([question, answer]) => <details key={question}><summary>{question}<ChevronRight size={18} /></summary><p>{answer}</p></details>)}</div></section>
    <section className="final-cta"><div className="container"><div><span className="eyebrow">Make your next connection a secure one.</span><h2>Your domain is ready for HTTPS.</h2></div><GlassButton asChild variant="primary" size="lg"><Link href="/generate">Generate your free SSL <ArrowRight /></Link></GlassButton></div></section>
  </>;
}